apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container
          image: muyleangin/reactjs:1.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: spring-volume
              mountPath: /app/src/main/resources/images
      volumes:
        - name: spring-volume
          nfs: 
            server: 128.199.148.26
            path: /opt/nfs/data
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  
spec:
  selector:
    app: spring-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - backend.sen-pai.live
      secretName: springapp-tls
  rules:
    - host: backend.sen-pai.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-service
                port:
                  number: 80
