apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  labels:
    app: springapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: spring-container
          image: 69966/springgradleimg:1.1.1
          ports:
            - containerPort: 8080
          volumeMoutns:
            - name: springapp-vol
              mountPath: /app/src/main/resources/images
      volumes:
        - name: springapp-vol
          nfs:
            server: 128.199.148.26
            path: /opt/nfs/data
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  type: ClusterIP
  selector:
    app: springapp
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - backend.sen-pai.live
      secretName: springapp-tls
  rules:
    - host: backend.sen-pai.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springapp
                port:
                  number: 8080
